### ISSUE TITLE
Mulighet for å vise klokkeslett

### ISSUE THREAD

**Issue by ariselseng** [stigok/ruterstop#53]
Det hadde vært kult man kunne vist klokkeslett hvis det var over en viss tid igjen. Slik ofte skilt pleier å være.

**Comment by ariselseng** [comment]
Det var forresten et veldig kult prosjekt dette. Jeg bruker det med denne plasma-widgeten på min desktop: https://store.kde.org/p/1173112/

**Comment by stigok** [comment]
Så hyggelig at du liker det!
Ja, det kan være en god idé. Vi kan jo for eksempel vise det for alle tider > 59 min.

**Comment by stigok** [comment]
@ariselseng ping!

**Comment by ariselseng** [comment]
@stigok Jeg fant ut at det ikke finnes sanntid for Agder i entur-apiet. Så jeg har gått over til å bruke noe annet.
Jeg vil si at > 59 min er en grei default, men helt ideelt hadde nok vært om man kan konfigurere det.
